
package:
    name: sqlparams
    version: 4.0.0

source:
    url: https://files.pythonhosted.org/packages/17/34/7a9675b60424d065504bc54dca780319ad0d72184ef06875c64dc8276bec/sqlparams-4.0.0.tar.gz
    sha256: 1d917944325f2ebc400d0a60ea8646f7cee18221924a6c53db94b1012aea6053

build:
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
    run:
        - python

about:
    home: https://python-sql-parameters.readthedocs.io/en/latest/index.html
    license: MIT
    summary: Convert DB API 2.0 named parameters to ordinal parameters
    doc_url: https://python-sql-parameters.readthedocs.io/en/latest/index.html
    dev_url: https://github.com/cpburnz/python-sql-parameters
