name: Publish conda package

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda update conda
        conda install conda-build

    - name: Build package
      run: |
        mkdir artifacts
        conda build --no-anaconda-upload --output-folder artifacts .

    - name: Publish package
      run: |
        anaconda upload --no-progress --user SingleStore --token ${{ secrets.ANACONDA_TOKEN }} artifacts/sqlparams-*.tar.bz2
